#!/usr/bin/env bash
# HAproxy installation and configuration

sudo apt-get -y update
sudo apt-get -y install haproxy
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 6199-web-01 54.208.174.206:80 check
        server 56199-web-02 54.160.32.83:80 check

frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart