#!/bin/bash

sudo apt update
sudo apt install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 http://example.com;
    }
}
EOL

sudo nginx -t
sudo service nginx start
